### ISSUE TITLE
URL to thesis not working

### ISSUE THREAD

**Issue by RLumSK** [SteveGrehl/tubaf-gripper#1]
The URL to the thesis is not working. The markdown code reads: 

`Thesis: [Autonomous Instrumentation of old underground mines using a mobile manipulator](thesis.steve-grehl.de)`

while it should read: 

`Thesis: [Autonomous Instrumentation of old underground mines using a mobile manipulator](https://nbn-resolving.org/urn:nbn:de:bsz:105-qucosa2-762699)`

Somewhat the redirection via `thesis.steve-grehl.de` (without `https://` or so) does not work.

**Comment by SteveGrehl** [comment]
Thanks 😀
